In [3]:
import pandas as pd
import numpy as np

In [4]:
#baby_names = pd.read_csv("baby_names.csv", encoding="windows-1252")

In [5]:
#baby_names = pd.read_csv("baby_names.csv", encoding="windows-1252", header=[8, 9], skip_footer=3, engine="python")

In [6]:
maindf = pd.read_csv("Consumer_Complaints.csv", dtype=str)

In [7]:
maindf['Complaint ID'] = maindf['Complaint ID'].astype(np.int64)

In [10]:
date_column = maindf.pop('Date received')

In [11]:
maindf['Date received'] = pd.to_datetime(date_column, format="%m/%d/%Y")

In [12]:
comp_by_month = maindf

In [14]:
comp_by_month.index = maindf['Date received']

In [43]:
maindf.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 409400 entries, 2015-06-22 to 2011-12-01
Data columns (total 14 columns):
Complaint ID            409400 non-null int64
Product                 409400 non-null object
Sub-product             280534 non-null object
Issue                   409394 non-null object
Sub-issue               128913 non-null object
State                   403759 non-null object
ZIP code                404783 non-null object
Submitted via           409400 non-null object
Date sent to company    409400 non-null object
Company                 409400 non-null object
Company response        409400 non-null object
Timely response?        409400 non-null object
Consumer disputed?      377841 non-null object
Date received           409400 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(12)
memory usage: 46.9+ MB

In [16]:
maindf.head()

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
Date received,,,,,,,,,,,,,,
2015-06-22,1431865,Consumer loan,Vehicle loan,Managing the loan or lease,NaN,NJ,08736,Web,06/22/2015,Nissan Motor Acceptance Corporation,In progress,Yes,NaN,2015-06-22
2015-06-22,1431374,Debt collection,Medical,Disclosure verification of debt,Not given enough info to verify debt,WI,54140,Web,06/22/2015,"RSI Enterprises, Inc.",Closed with explanation,Yes,NaN,2015-06-22
2015-06-22,1431251,Mortgage,Conventional fixed mortgage,"Loan modification,collection,foreclosure",NaN,MO,63368,Web,06/22/2015,Flagstar Bank,In progress,Yes,NaN,2015-06-22
2015-06-22,1431743,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,WA,98055,Web,06/22/2015,"P.S.C., Inc",Closed with explanation,Yes,Yes,2015-06-22
2015-06-22,1432678,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt was paid,TX,75104,Web,06/22/2015,"ProCollect, Inc",Closed with explanation,Yes,NaN,2015-06-22

In [17]:
maindf.tail()

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
Date received,,,,,,,,,,,,,,
2011-12-01,2352,Credit card,NaN,Credit determination,NaN,NY,13350,Web,12/05/2011,Capital One,Closed without relief,Yes,Yes,2011-12-01
2011-12-01,2366,Credit card,NaN,Credit reporting,NaN,FL,33415,Referral,12/06/2011,Citibank,Closed without relief,Yes,Yes,2011-12-01
2011-12-01,2368,Credit card,NaN,Credit line increase/decrease,NaN,FL,32792,Web,12/05/2011,Citibank,Closed without relief,Yes,No,2011-12-01
2011-12-01,2371,Credit card,NaN,Other fee,NaN,HI,96813,Web,12/19/2011,Capital One,Closed without relief,Yes,No,2011-12-01
2011-12-01,2374,Credit card,NaN,Payoff process,NaN,CA,94108,Phone,12/05/2011,Capital One,Closed without relief,Yes,Yes,2011-12-01

In [18]:
comp_by_month_df = maindf

In [81]:
comp_by_month_df = comp_by_month_df.groupby(lambda x: x.month).count()

In [82]:
comp_by_month_df

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
1,38378,38378,26026,38378,12500,37888,37989,38378,38378,38378,38378,38378,37727,38378
2,37602,37602,24832,37600,12790,37056,37237,37602,37602,37602,37602,37602,36830,37602
3,43493,43493,29690,43493,14021,42921,43069,43493,43493,43493,43493,43493,41299,43493
4,41970,41970,28685,41970,13450,41369,41543,41970,41970,41970,41970,41970,33868,41970
5,41434,41434,28676,41434,12557,40843,40913,41434,41434,41434,41434,41434,29631,41434
6,34117,34117,23669,34117,9719,33627,33702,34117,34117,34117,34117,34117,28401,34117
7,29518,29518,20808,29518,8293,29125,29097,29518,29518,29518,29518,29518,28925,29518
8,29602,29602,20936,29602,8647,29264,29282,29602,29602,29602,29602,29602,29310,29602
9,27665,27665,19292,27664,8846,27360,27346,27665,27665,27665,27665,27665,27359,27665
10,28878,28878,20157,28875,8926,28476,28548,28878,28878,28878,28878,28878,28589,28878
11,26714,26714,17948,26714,9526,26288,26389,26714,26714,26714,26714,26714,26394,26714
12,30029,30029,19815,30029,9638,29542,29668,30029,30029,30029,30029,30029,29508,30029

In [20]:
comp_by_product_df = maindf.groupby("Product").count()

In [21]:
comp_by_product_df

,Complaint ID,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
Product,,,,,,,,,,,,,
Bank account or service,47166,47166,47162,0,46230,46305,47166,47166,47166,47166,47166,44730,47166
Consumer loan,13771,13771,13769,0,13632,13609,13771,13771,13771,13771,13771,12666,13771
Credit card,51103,0,51103,0,50548,50473,51103,51103,51103,51103,51103,48529,51103
Credit reporting,60006,0,60006,60006,58475,59568,60006,60006,60006,60006,60006,52516,60006
Debt collection,68907,53805,68907,68907,68065,68246,68907,68907,68907,68907,68907,61004,68907
Money transfers,2383,2383,2383,0,2281,2323,2383,2383,2383,2383,2383,2110,2383
Mortgage,150140,150140,150140,0,148819,148477,150140,150140,150140,150140,150140,141705,150140
Other financial service,227,227,227,0,216,223,227,227,227,227,227,183,227
Payday loan,2655,0,2655,0,2590,2633,2655,2655,2655,2655,2655,2276,2655
Prepaid card,784,784,784,0,771,774,784,784,784,784,784,644,784
Student loan,12258,12258,12258,0,12132,12152,12258,12258,12258,12258,12258,11478,12258

In [64]:
comp_by_company_df = maindf.groupby("Company").count()

In [77]:
comp_by_company_df.sort('Complaint ID')[:-10:-1]

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company response,Timely response?,Consumer disputed?,Date received
Company,,,,,,,,,,,,,
Bank of America,47753,47753,41837,47753,890,47204,47115,47753,47753,47753,47753,45581,47753
Wells Fargo,33781,33781,31289,33780,747,33349,33291,33781,33781,33781,33781,32420,33781
JPMorgan Chase,26745,26745,20558,26744,920,26405,26410,26745,26745,26745,26745,25582,26745
Experian,21112,21112,71,21112,21032,20647,20952,21112,21112,21112,21112,18494,21112
Equifax,20592,20592,53,20592,20527,20058,20459,20592,20592,20592,20592,18334,20592
Citibank,20024,20024,10438,20024,1572,19758,19768,20024,20024,20024,20024,18967,20024
Ocwen,17331,17331,17276,17331,355,17199,17159,17331,17331,17331,17331,16390,17331
TransUnion,16010,16010,35,16010,15982,15477,15879,16010,16010,16010,16010,13743,16010
Capital One,12378,12378,3793,12377,1216,12229,12221,12378,12378,12378,12378,11750,12378

In [61]:
comp_by_company_df[:-10:-1]

Date received           47753
Consumer disputed?      45581
Timely response?        47753
Company response        47753
Date sent to company    47753
Submitted via           47753
ZIP code                47115
State                   47204
Sub-issue               21032
dtype: int64

In [24]:
comp_by_company_res_df = maindf.groupby("Company response", sort=True).count()

In [25]:
comp_by_company_res_df

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Timely response?,Consumer disputed?,Date received
Company response,,,,,,,,,,,,,
Closed,9909,9909,8274,9909,3469,9749,9772,9909,9909,9909,9909,9128,9909
Closed with explanation,289933,289933,209919,289929,89953,285923,286586,289933,289933,289933,289933,269270,289933
Closed with monetary relief,28910,28910,17680,28908,1578,28563,28538,28910,28910,28910,28910,27459,28910
Closed with non-monetary relief,52257,52257,24758,52257,31419,51340,51747,52257,52257,52257,52257,48940,52257
Closed with relief,5305,5305,2784,5305,0,5261,5252,5305,5305,5305,5305,5229,5305
Closed without relief,17909,17909,13600,17909,0,17807,17757,17909,17909,17909,17909,17813,17909
In progress,3153,3153,2057,3153,1247,3119,3129,3153,3153,3153,3153,0,3153
Untimely response,2024,2024,1462,2024,1247,1997,2002,2024,2024,2024,2024,2,2024

In [45]:
comp_by_DOW_df = maindf
comp_by_DOW_df = comp_by_DOW_df.resample('weekday', how="count")

In [47]:
comp_by_DOW_df = maindf
comp_by_DOW_df = comp_by_DOW_df.groupby(lambda x: x.weekday).count()

In [48]:
comp_by_DOW_df

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
0,73802,73802,51540,73800,21945,72817,72844,73802,73802,73802,73802,73802,68393,73802
1,77286,77286,53057,77285,23975,76115,76388,77286,77286,77286,77286,77286,71097,77286
2,79251,79251,55107,79250,24235,78094,78363,79251,79251,79251,79251,79251,73136,79251
3,75729,75729,52632,75727,23592,74627,74865,75729,75729,75729,75729,75729,69776,75729
4,66564,66564,45951,66564,20695,65538,65800,66564,66564,66564,66564,66564,61455,66564
5,19883,19883,11977,19883,7883,19766,19735,19883,19883,19883,19883,19883,18417,19883
6,16885,16885,10270,16885,6588,16802,16788,16885,16885,16885,16885,16885,15567,16885

# Number of complaints by month

In [83]:
comp_by_month_df

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
1,38378,38378,26026,38378,12500,37888,37989,38378,38378,38378,38378,38378,37727,38378
2,37602,37602,24832,37600,12790,37056,37237,37602,37602,37602,37602,37602,36830,37602
3,43493,43493,29690,43493,14021,42921,43069,43493,43493,43493,43493,43493,41299,43493
4,41970,41970,28685,41970,13450,41369,41543,41970,41970,41970,41970,41970,33868,41970
5,41434,41434,28676,41434,12557,40843,40913,41434,41434,41434,41434,41434,29631,41434
6,34117,34117,23669,34117,9719,33627,33702,34117,34117,34117,34117,34117,28401,34117
7,29518,29518,20808,29518,8293,29125,29097,29518,29518,29518,29518,29518,28925,29518
8,29602,29602,20936,29602,8647,29264,29282,29602,29602,29602,29602,29602,29310,29602
9,27665,27665,19292,27664,8846,27360,27346,27665,27665,27665,27665,27665,27359,27665
10,28878,28878,20157,28875,8926,28476,28548,28878,28878,28878,28878,28878,28589,28878
11,26714,26714,17948,26714,9526,26288,26389,26714,26714,26714,26714,26714,26394,26714
12,30029,30029,19815,30029,9638,29542,29668,30029,30029,30029,30029,30029,29508,30029

# Number of complaints by product

In [79]:
comp_by_product_df

,Complaint ID,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
Product,,,,,,,,,,,,,
Bank account or service,47166,47166,47162,0,46230,46305,47166,47166,47166,47166,47166,44730,47166
Consumer loan,13771,13771,13769,0,13632,13609,13771,13771,13771,13771,13771,12666,13771
Credit card,51103,0,51103,0,50548,50473,51103,51103,51103,51103,51103,48529,51103
Credit reporting,60006,0,60006,60006,58475,59568,60006,60006,60006,60006,60006,52516,60006
Debt collection,68907,53805,68907,68907,68065,68246,68907,68907,68907,68907,68907,61004,68907
Money transfers,2383,2383,2383,0,2281,2323,2383,2383,2383,2383,2383,2110,2383
Mortgage,150140,150140,150140,0,148819,148477,150140,150140,150140,150140,150140,141705,150140
Other financial service,227,227,227,0,216,223,227,227,227,227,227,183,227
Payday loan,2655,0,2655,0,2590,2633,2655,2655,2655,2655,2655,2276,2655
Prepaid card,784,784,784,0,771,774,784,784,784,784,784,644,784
Student loan,12258,12258,12258,0,12132,12152,12258,12258,12258,12258,12258,11478,12258

# Number of complaints by company (top 10)

In [78]:
comp_by_company_df.sort('Complaint ID')[:-10:-1]

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company response,Timely response?,Consumer disputed?,Date received
Company,,,,,,,,,,,,,
Bank of America,47753,47753,41837,47753,890,47204,47115,47753,47753,47753,47753,45581,47753
Wells Fargo,33781,33781,31289,33780,747,33349,33291,33781,33781,33781,33781,32420,33781
JPMorgan Chase,26745,26745,20558,26744,920,26405,26410,26745,26745,26745,26745,25582,26745
Experian,21112,21112,71,21112,21032,20647,20952,21112,21112,21112,21112,18494,21112
Equifax,20592,20592,53,20592,20527,20058,20459,20592,20592,20592,20592,18334,20592
Citibank,20024,20024,10438,20024,1572,19758,19768,20024,20024,20024,20024,18967,20024
Ocwen,17331,17331,17276,17331,355,17199,17159,17331,17331,17331,17331,16390,17331
TransUnion,16010,16010,35,16010,15982,15477,15879,16010,16010,16010,16010,13743,16010
Capital One,12378,12378,3793,12377,1216,12229,12221,12378,12378,12378,12378,11750,12378

# Number of complaints by company response

In [50]:
comp_by_company_res_df

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Timely response?,Consumer disputed?,Date received
Company response,,,,,,,,,,,,,
Closed,9909,9909,8274,9909,3469,9749,9772,9909,9909,9909,9909,9128,9909
Closed with explanation,289933,289933,209919,289929,89953,285923,286586,289933,289933,289933,289933,269270,289933
Closed with monetary relief,28910,28910,17680,28908,1578,28563,28538,28910,28910,28910,28910,27459,28910
Closed with non-monetary relief,52257,52257,24758,52257,31419,51340,51747,52257,52257,52257,52257,48940,52257
Closed with relief,5305,5305,2784,5305,0,5261,5252,5305,5305,5305,5305,5229,5305
Closed without relief,17909,17909,13600,17909,0,17807,17757,17909,17909,17909,17909,17813,17909
In progress,3153,3153,2057,3153,1247,3119,3129,3153,3153,3153,3153,0,3153
Untimely response,2024,2024,1462,2024,1247,1997,2002,2024,2024,2024,2024,2,2024

# Number of complaints by day of week

In [49]:
comp_by_DOW_df

,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Submitted via,Date sent to company,Company,Company response,Timely response?,Consumer disputed?,Date received
0,73802,73802,51540,73800,21945,72817,72844,73802,73802,73802,73802,73802,68393,73802
1,77286,77286,53057,77285,23975,76115,76388,77286,77286,77286,77286,77286,71097,77286
2,79251,79251,55107,79250,24235,78094,78363,79251,79251,79251,79251,79251,73136,79251
3,75729,75729,52632,75727,23592,74627,74865,75729,75729,75729,75729,75729,69776,75729
4,66564,66564,45951,66564,20695,65538,65800,66564,66564,66564,66564,66564,61455,66564
5,19883,19883,11977,19883,7883,19766,19735,19883,19883,19883,19883,19883,18417,19883
6,16885,16885,10270,16885,6588,16802,16788,16885,16885,16885,16885,16885,15567,16885

The day of the week that had the most complaints was Wednesday.
Most companies closed the complaint with an explanation.
Bank of America and Wells Fargo were the companies with the highest number of complaints
Mortgage and Debt collection were the products most complained about
March had the highest number of complaints per month